version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: qlpk_mysql
    environment:
      MYSQL_DATABASE: mrhdev
      MYSQL_USER: mrhdev
      MYSQL_PASSWORD: mrhdev123
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - qlpk_network
    volumes:
      - qlpk_db:/var/lib/mysql

  redis:
    container_name: qlpk_redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - qlpk_network

networks:
  qlpk_network:
volumes:
  qlpk_db:
